[env]
TERM = "xterm-256color"

[font]
size = 7.0
offset.x = 0  # For letter spacing (default: 0)
offset.y = 2  # For line spacing (default: 0)

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window.padding]
x = 4
y = 0
